-- =========================
-- TABLA GENERO
-- =========================
CREATE TABLE GENERO(
	ID INT NOT NULL,
	valor VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID)
);

-- =========================
-- TABLA PERMISOS
-- =========================
CREATE TABLE PERMISOS(
	ID INT NOT NULL,
	valor VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID)
);

-- =========================
-- TABLA USUARIO
-- =========================
CREATE TABLE USUARIO(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	usuario VARCHAR(80) NOT NULL,
	contrasena VARCHAR(80) NOT NULL,
	rol VARCHAR(20) NOT NULL,
	ID_GENERO INT,
	PRIMARY KEY(ID)
);

ALTER TABLE USUARIO 
ADD CONSTRAINT USR_GEN 
FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID);

-- =========================
-- TABLA PRODUCTO
-- =========================
CREATE TABLE PRODUCTO(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(80) NOT NULL,
	precio INT NOT NULL,
	PRIMARY KEY(ID)
);

-- =========================
-- TABLA N:M PRODUCTO_USUARIO
-- =========================
CREATE TABLE PRODUCTO_USUARIO(
	ID_USUARIO BIGINT NOT NULL,
	ID_PRODUCTO BIGINT NOT NULL,
	PRIMARY KEY(ID_USUARIO, ID_PRODUCTO)
);

ALTER TABLE PRODUCTO_USUARIO 
ADD CONSTRAINT PU_USR 
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID);

ALTER TABLE PRODUCTO_USUARIO 
ADD CONSTRAINT PU_PROD 
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID);

-- =========================
-- TABLA N:M PERMISOS_USUARIOS
-- =========================
CREATE TABLE PERMISOS_USUARIOS(
	PERMISO_ID INT NOT NULL,
	USUARIO_ID BIGINT NOT NULL,
	PRIMARY KEY(PERMISO_ID, USUARIO_ID)
);

ALTER TABLE PERMISOS_USUARIOS 
ADD CONSTRAINT PUSR_PER 
FOREIGN KEY (PERMISO_ID) REFERENCES PERMISOS(ID);

ALTER TABLE PERMISOS_USUARIOS 
ADD CONSTRAINT PUSR_USR 
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID);